[package]
name = "ssh-upload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssh-sftp-client = "0.8.2"
ssh2 = "0.9.3"
tokio = { version = "1.17.0", features = ["full"] }
